version: 1
disable_existing_loggers: no
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  'null':
    class: logging.NullHandler
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

loggers:
  backoff:
    handlers: [console]
    propagate: no
    level: INFO
  django.security.DisallowedHost:
    handlers: ['null']
    propagate: no
  django:
    handlers: [console]
    propagate: yes
    level: INFO
  django.request:
    handlers: [console]
    propagate: no
    level: ERROR
  core:
    handlers: [console]
    propagate: no
    level: DEBUG
  "":
    handlers: [console]
    level: INFO
