name: push-front
on:
  workflow_dispatch:
  push:
    branches:
       - master
       - main
    paths:
       - 'frontend/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - run: |
              cd ./frontend
              npm install
              npm run test:unit
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: "Upload to transifex"
        run: |
              sudo apt-get install gettext
              cd ./frontend
              npm run gettext-extract
              pip install transifex-client
              export TX_TOKEN=${{ secrets.TX_TOKEN }}
              tx push -s

  build:
    runs-on: ubuntu-latest
    needs: tests
    env:
      CI: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: "Download from transifex"
        run: |
              pip install transifex-client
              cd ./frontend
              export TX_TOKEN=${{ secrets.TX_TOKEN }}
              tx pull -l es
      - name: Build container image
        uses: docker/build-push-action@v1
        with:
          path: ./frontend
          build_args: VUE_APP_API_URL=${{ secrets.API_URL }},VUE_APP_WEBSOCKET_URL=${{ secrets.WEBSOCKET_URL }},VUE_APP_SENTRY_DSN=${{ secrets.SENTRY_DSN }},SENTRY_ENVIRONMENT=${{ secrets.SENTRY_ENVIRONMENT }}
          username: ${{ secrets.R_USER }}
          password: ${{ secrets.R_SECRET }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/${{ secrets.FRONT_IMAGE_NAME }}
          tag_with_sha: true
          tag_with_ref: true
          tags: latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      CI: true
    steps:
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7
      - name: Deploy docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
              cd git
              docker login -u ${{ secrets.R_USER }} -p ${{ secrets.R_SECRET }}  docker.pkg.github.com/${{ github.repository }}/
              docker-compose -f docker-compose.deploy.yaml pull front &&
              docker-compose -f docker-compose.deploy.yaml stop front &&
              docker-compose -f docker-compose.deploy.yaml up -d front
