name: pull-request-front
on:
  push:
    branches:
       - master
       - main
    paths:
       - 'frontend/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - run: |
              cd ./frontend
              npm install
              npm run test:unit
